devschool_admin:
    resource: "@DevschoolAdminBundle/Controller/"
    type:     annotation
    prefix:   /

devschool_cinema:
    resource: "@DevschoolCinemaBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
