<?php

namespace Devschool\CinemaBundle\Repository;

/**
 * RealisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
